[package]
name = "get-noting"
version = "0.1.0"
description = "A simple note-taking app"
authors = ["Dylan Claywell"]
license = "MIT"
repository = "https://github.com/dylanclaywell/get-noting"
default-run = "get-noting"
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0-rc.12", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.0-rc.14", features = ["window-close", "window-maximize", "window-minimize", "window-start-dragging", "window-unmaximize"] }
sqlite = "0.26.0"
uuid = { version = "1.1.1", features = ["v4","fast-rng","macro-diagnostics"] }
window-shadows = "0.1.3"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
